<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::table('meeting_summaries', function (Blueprint $table) {
            // Allow creating media records before summary is generated by the background job
            $table->text('summary')->nullable()->change();
        });
    }

    public function down(): void
    {
        Schema::table('meeting_summaries', function (Blueprint $table) {
            // Revert to NOT NULL summary
            $table->text('summary')->nullable(false)->change();
        });
    }
};
