FROM php:8.2-fpm

# Install dependencies and extensions
RUN docker-php-ext-install mysqli

RUN apt-get -y update --fix-missing && \
    apt-get upgrade -y && \
    apt-get --no-install-recommends install -y apt-utils && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get -y update && \
    apt-get -y --no-install-recommends install nano wget \
dialog \
libsqlite3-dev \
libsqlite3-0 && \
    apt-get -y --no-install-recommends install default-mysql-client \
zlib1g-dev \
libzip-dev \
libicu-dev && \
    apt-get -y --no-install-recommends install --fix-missing apt-utils \
build-essential \
git \
curl \
libonig-dev && \
    apt-get -y --no-install-recommends install --fix-missing libcurl4 \
libcurl4-openssl-dev \
pkg-config \
libssl-dev \
zip \
openssl && \
    rm -rf /var/lib/apt/lists/* && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install pdo && \
    docker-php-ext-install pdo_mysql

RUN    docker-php-ext-install pdo_sqlite && \
    docker-php-ext-install mysqli
RUN    docker-php-ext-install curl
#    docker-php-ext-install tokenizer

RUN    docker-php-ext-install zip && \
    docker-php-ext-install -j$(nproc) intl && \
    docker-php-ext-install mbstring
RUN    docker-php-ext-install gettext && \
    docker-php-ext-install exif

RUN docker-php-ext-install pcntl

RUN apt-get update && \
pecl install redis && \
docker-php-ext-enable redis

RUN echo "upload_max_filesize=50M\npost_max_size=60M\nmemory_limit=512M" > /usr/local/etc/php/conf.d/uploads.ini

RUN pecl install pcov \
    && docker-php-ext-enable pcov
ENV PCOV_ENABLED=1


RUN apt-get -y update && \
    apt-get --no-install-recommends install -y libfreetype6-dev \
libjpeg62-turbo-dev \
libpng-dev && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd
